{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1 
    name: {{ .Values.name }}
    kind: Deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.averageUtilization }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization 
        averageUtilization: {{ .Values.hpa.targetAverageUtilization }}
{{- end }}
