apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ include "go-ejlog-server-ocp.fullname" . }}
  name: {{ include "go-ejlog-server-ocp.fullname" . }}
spec:
  {{- if eq .Values.env "dev" }}
  host: "{{ include "go-ejlog-server-ocp.fullname" . }}{{ .Values.dev.host }}"
  {{- else if eq .Values.env "dc" }}
  host: "{{ include "go-ejlog-server-ocp.fullname" . }}{{ .Values.dc.host }}"
  {{- else }}
  host: "{{ include "go-ejlog-server-ocp.fullname" . }}{{ .Values.dr.host }}"
  {{- end }}
  path: 
  port:
    targetPort: {{ .Values.targetPort }}
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: {{ .Values.service.weight }}
  wildcardPolicy: None
status:
  ingress:
    - conditions:
      {{- if eq .Values.env "dev" }}
      host: "{{ include "go-ejlog-server-ocp.fullname" . }}{{ .Values.dev.host }}"
      {{- else if eq .Values.env "dc" }}
      host: "{{ include "go-ejlog-server-ocp.fullname" . }}{{ .Values.dc.host }}"
      {{- else }}
      host: "{{ include "go-ejlog-server-ocp.fullname" . }}{{ .Values.dr.host }}"
      {{- end }}
      routerName: router
      wildcardPolicy: None
      routerCanonicalHostname: {{ .Values.host }}