apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-ejlog-server-ocp.fullname" . }}
  labels:
    {{- include "go-ejlog-server-ocp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.targetPort }}
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    {{- include "go-ejlog-server-ocp.selectorLabels" . | nindent 4 }}
